### ISSUE TITLE
DREAMS FY18Q1 Dashboard QC

### ISSUE THREAD

**Issue by kimisatoPC** [ICPI/Prevention-Cluster#1]
Dashboard ready for QC and QC protocol updated [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FPrevention%2FWorking%20Folder%2FDREAMS&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

**Comment by kimisatoPC** [comment]
@shapaklyak @erinschelar @hessionra Katya is working on a template to better track the results of the QC. Also, please know that QC-ing one OU per QC section is sufficient.

**Comment by erinschelar** [comment]
My checks all passed with the exception of PrEP_NEW and VMMC_CIRC for Cote d'Ivoire. CDI had no data for either of these indicators...let me know if you want me to check another OU for those two indicators.

**Comment by shapaklyak** [comment]
@kimisatoPC sent you checks regarding PMTCT_STAT and completeness.  PMTCT STAT was doubling on the Completeness check and FY18 Achievement by AgeSex, and FY18 Quarterly Trends tabs. I know you've made the adjustments already, this is for others' fyi.

**Comment by hessionra** [comment]
@kimisatoPC @erinschelar everything checked out for my assignments! Sent you my check sheet on 3/8 at 10:55a.

Thanks!
