### ISSUE TITLE
QC needed on Prevention Reference Dashboard

### ISSUE THREAD

**Issue by kimisatoPC** [ICPI/Prevention-Cluster#13]
[Prevention Reference Tableau dashboard posted here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FPrevention%2FWorking%20Folder%2FCross%2DCutting%2FFY18%2C%20Q2&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

Katya or Erin can you QC against Pano please?

**Comment by shapaklyak** [comment]
Running list of QC checks

- [x ] PP_PREV by OU - Checked Botswana for FY17 and FY18 data
