### ISSUE TITLE
Prevention Reference Tables QC

### ISSUE THREAD

**Issue by kimisatoPC** [ICPI/Prevention-Cluster#2]
Request from Caroline Cooney via Heather Watts to QC the [Prevention Reference Tables](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FPrevention%2FRPM%202%20Prevention%20Reference%20Tables&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D) sent out during RPMs. Now that Panorama includes Q2/Q4 data, the data don't match in Pano vs. final.datim vs. [Tableau dashboard. ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FPrevention&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

Kimi will check PP_PREV, GEND_GBV, KP_PREV
Katya: OVC_SERV

**Comment by shapaklyak** [comment]
**Review of FY17 Results**

Error in nb.3 below
will continue to review additional Tableau tabs

Nb. |Level | Tableau | Pano | final.datim | OVC dashboard
-|----- | -------------|------------ | -------------|------------
1| OVC_SERV by OU Total N (program status) | 14,241 | 14,241 | 14,241 | 14,241
2| OVC_SERV by IM Total N (program status) | 14,241 | 14,241 | not checked | 14,241
3| OVC_SERV by PSNU Total N (program status) | **2,894**| 1,418| 1,418 | **8,114**

**Comment by shapaklyak** [comment]
- Error in nb.4 below in Panorama percentage calculating program status: 10,978/14,241 is not 93%, will be submitting zendesk ticket 

Nb. |Level | Tableau | Pano | final.datim | OVC dashboard
-|----- | -------------|------------ | -------------|------------
1| OVC_SERV by OU Total N (program status) | 14,241 | 14,241 | 14,241 | 14,241
2| OVC_SERV by IM Total N (program status) | 14,241 | 14,241 | not checked | 14,241
3*| OVC_SERV by PSNU Total N (program status) | **2,894**| 1,418| 1,418 | **8,114**
4*| OVC SERV Program status FY17APR | 77.1% Active | **93% Active** | 77.1 % Active | 77.1% Active

**Comment by shapaklyak** [comment]
Disregard the OVC Tableau QC fail (nb3) - was using an older version. The 02-27 Tableau workbook doesn't have OVC in it. Inconsistency in OVC dashboard (nb3) and Panorama (nb4) still stand though.

**Comment by kimisatoPC** [comment]
Panorama Global View summing Numerator and Denominator values. 

Recommendation to use final.datim OR Prevention reference tables. Kimi will submit a Pano zendesk ticket regarding data issue.
