### ISSUE TITLE
QC FY19Q1 DREAMS Dashboard

### ISSUE THREAD

**Issue by kimisatoPC** [ICPI/Prevention-Cluster#26]
The DREAMS MSD will be released on Friday, 2/22 and I am hoping to update it that same day. The dashboard should be ready to QC on Monday, 2/25. Are you available to QC the dashboard by COB 2/25?

**Comment by kimisatoPC** [comment]
@hessionra @shapaklyak 

![image](https://user-images.githubusercontent.com/36009724/52804271-da08ba00-3051-11e9-8b49-23b7445e07f0.png)

Updated [QC guidance posted here.](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FPrevention%2FWorking%20Folder%2FDREAMS%2FFY19%2C%20Q1&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

**Comment by shapaklyak** [comment]
I will NOT be available on 2/25, however I could possibly QC on the morning of 2/26.

**Comment by kimisatoPC** [comment]
[FY19Q1 DREAMS dashboard](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FPrevention%2FWorking%20Folder%2FDREAMS%2FFY19%2C%20Q1&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D) is ready for QC! @shapaklyak @hessionra

**Comment by hessionra** [comment]
|QC Section | Indicator/Country | Pass?|
|---|---|---|
|Tab to Tab 2c Check | HST_TST Eswatini | ☑️|
|Tab to Raw Data | TX CURR Botswana | |
|Tab to Raw Data | PMTCT_STAT CDI | |
|Tab to Raw Data | HTS_TST Haiti | |
