### ISSUE TITLE
OVC Dashboard Updates

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/Prevention-Cluster#3]
List of identified issues with current state OVC dashboard.

- [x]  Results and Trends by SNU tab: bottom graph needs to be filtered to OVC SERV indicator

**Comment by shapaklyak** [comment]
**Completeness**
- [ ] Update to new OVC SERV total numerator

**Results-Targets by OU**
- [ ]  a) combine first two charts that use age/sex disaggregate (under 18 and total n using age/sex) into one chart; perhaps a stacked bar chart with under 18 and then on top rest of the OVC SERV numbers. For comparing results vs. targets. 
- [ ]  b) include table that shows both under 18 and total OVC SERV using age/sex disaggs 
- [ ]  c) put this chart at the top since it is the actual definition of total numerator. update total N to = active + grad only. 

**Results by Age & Sex**
- [ ] a) change under 10 from grey to a different color (maybe darker green?).
- [ ] b) add targets for each fine age/sex disagg
- [ ] c) move summary chart up to the top  left and breakout into fine age/sex bands chart. Add percentages of groupings within chart or remove this summary chart
- [ ] d) add PSNU slicer or view to this tab

**Program Status**
- [ ] a) revise stacked bar chart to reflect total N = active + grad; and other disaggs
- [ ] b) revise pie charts as in mockup 
- [ ] c) Program status by SNU: only total N, stacked bar chart with active & grad (remove other disaggs); need something for transferred/exited
- [ ] d) PSNU slicer - add 2 columns
- [ ] e) check OU Selection label (top left)

**Results and Trends by SNU (geographic)**
****rethink this visual, perhaps not by prioritization by other categories for OVC SERV
- [ ] a) move results and targets by SNU to top

**Trends for OVC_SERV** - separate analysis from dashboard - trends for OVC SERV (results and targets, in comparison to budget) 
- [ ] a) add disclaimer of change in OVC SERV total N, that it was applied to FY17 and FY18 (in notes section and on chart?)
- [ ] b) update colors?
- [ ] c) move chart from Results and Trends by SNU over 

**Results by Agency and IM**
- [ ] a) rename tab to "results and targets by agency and IM"
- [ ] b) revise Under 18 chart so targets are a blue line and % achievement yellow circle

**OVC_HIVSTAT**
country view
- [ ] a) add proportions for % receiving ART of HIV positives (similar to panorama)
- [ ] b) discuss completeness graphic 

global views
- [ ] a) HIV status undisclosed - update graphic; would want to see undisclosed going down in trends; and other reasons/test not indicated across OUs over time.
- [ ] b) maybe split out into two tabs: country view and global view
- [ ] c) remove completeness dots for table 1 and 2, swap % reporting completeness and % receiving ART; where to put completeness if split out into 2 tabs: country and global view
- [ ] d) check color conditional formatting on table 1 & 2

**MER ESI**
- [ ] remove tab

**Narratives**
- [ ] update/remove

**Comment by shapaklyak** [comment]
Updated above: Q2 test dataset will now be available on 4/20 per 4/16 inbrief
@erinschelar

**Comment by shapaklyak** [comment]
update: Q2 test dataset will now be available 4/23 or 4/24 @erinschelar @AmyAberra

**Comment by shapaklyak** [comment]
@KaeAnneParris @erinschelar @AmyAberra 
above updates pending Q2 test dataset release (estimate this week)

**Comment by shapaklyak** [comment]
Updates completed

**Comment by KaeAnneParris** [comment]
Where is the dashboard stored?

Thanks.

__________________________
Best,
KaeAnne Parris, MPH
Pediatric and Adolescent HIV Team | MCHB | DGHT | CDC
Office:   404-639-2493 | Mobile: 404-804-0261 | F: 404-471-8675
Email: KAParris@cdc.gov<mailto:KAParris@cdc.gov>

**Comment by KaeAnneParris** [comment]
Thanks! And use v3?

__________________________
Best,
KaeAnne Parris, MPH
Pediatric and Adolescent HIV Team | MCHB | DGHT | CDC
Office:   404-639-2493 | Mobile: 404-804-0261 | F: 404-471-8675
Email: KAParris@cdc.gov<mailto:KAParris@cdc.gov>
