### ISSUE TITLE
OVC Dashboard FY18Q2 QC

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/Prevention-Cluster#6]
List of QC'ers:

- KaeAnne
- Megan M.

**Comment by shapaklyak** [comment]
Estimated QC period: May 23-31.

**Comment by shapaklyak** [comment]
+ Nashiva & Shaylee

**Comment by shapaklyak** [comment]
QC moved to Tuesday-Wednesday, 5-29 to 5-30

**Comment by KaeAnneParris** [comment]
And Thursday?

__________________________
Best,
KaeAnne Parris, MPH
Pediatric and Adolescent HIV Team | MCHB | DGHT | CDC
Office:   404-639-2493 | Mobile: 404-804-0261 | F: 404-471-8675
Email: KAParris@cdc.gov<mailto:KAParris@cdc.gov>

**Comment by shapaklyak** [comment]
@KaeAnneParris yes, updated now :)

**Comment by shapaklyak** [comment]
@KaeAnneParris please use this ticket for conversation related to QC. 
The dashboard and QC materials are stored at the link below. Please email Erin & I your QC template or post it to the same folder. Don't post any data here. Thanks! You can comment on here when you've completed your QC. https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FPrevention%2FWorking%20Folder%2FOVC%2FPending%20QC&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence

**Comment by mehtasp** [comment]
Hi all, Uganda OVC QC is done and posted on Sharepoint using the link Katya sent out (above).

**Comment by erinschelar** [comment]
Swaziland complete and matches. 

For the cascade tab, I think we may want to make the visuals for no status match exactly the above for ART (i.e. add in the bar chart on completeness).

**Comment by AmyAberra** [comment]
Ethiopia complete and matches, although their results for HIVSTAT don't look great. Womp womp. Can I also just say, our dashboard is amazing. Thank you @shapaklyak

**Comment by shapaklyak** [comment]
@erinschelar identified an issue with Figure 2 on the OVC_HIVSTAT x OU tab; this pointing to the incorrect country list, this has now been corrected and a new version dated 6/8/2018 has been posted to the [Products Folder](https://www.pepfar.net/OGAC-HQ/icpi/Products/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FProducts%2FICPI%20Approved%20Tools%20%28Most%20Current%20Versions%29&FolderCTID=0x0120004DAC66286D0B8344836739DA850ACB95&View=%7B58E3102A%2DC027%2D4C66%2DA5C7%2D84FEBE208B3C%7D)
