### ISSUE TITLE
FY18 Q2 clean data QC

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/Prevention-Cluster#9]
QC tentatively scheduled for 7/3-7/6. Final tools due July 9th.

**Comment by shapaklyak** [comment]
@erinschelar please see updated dashboard [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Clusters/Prevention/Working%20Folder/OVC/DRAFTS/OVC%20Dashboard%20FY18Q2%202018%2007%2002%20clean%20working.xlsx)

I'm working on the OVC HIV STAT by SNU tab, so you can ignore that for now. All other tabs are ready for QC. Please QC a different country than last time. I believe Botswana's and Cameroon's data changed between unclean and clean based on the consistency check. Let me know what you think so far of the OVC HIV STAT by SNU tab...

**Comment by shapaklyak** [comment]
@erinschelar this seems to be an issue with how the values for transferexit are stored in the dataset and how it differs between results and targets. I'm going to have troubleshoot this more ...perhaps thursday morning or Monday morning unless you have time to take a stab at it. My Stata code is [here](https://github.com/ICPI/Prevention-Cluster/blob/master/OVC/Dashboard.do) but i'll try to convert it to R this week(?). let me know how that sounds..

**Comment by erinschelar** [comment]
Ok, so because of a change to the dataset or just an issue that wasn't caught last time? I am not sure how much time I'll have but if you don't get to it on Thursday I will just try to look at the Stata code so don't worry about converting it to R (better just to sort the issue if possible?).

**Comment by shapaklyak** [comment]
OVC Dashboard posted [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FPrevention%2FWorking%20Folder%2FOVC%2FPending%20QC&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence):

**Comment by shapaklyak** [comment]
QC Template located in [same folder as dashboard for QC on pepfar.net ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FPrevention%2FWorking%20Folder%2FOVC%2FPending%20QC&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence)
1. Pick a country
2. Compare FY18 Q2 results in each figure to Panorama or Datim favorite at the level of disaggregate displayed on the dashboard. 

@hessionra 

fyi @erinschelar 

- [ ] Completeness of Data 
- [ ] OVC SERV x OU
- [ ] OVC SERV by SNU
- [ ] OVC SERV x AgeSex
- [ ] OVC SERV x Prg Status
- [ ] OVC SERV x AgencyIM
- [ ] OVC HIVSTAT x OU
- [ ] OVC HIVSTAT Cascade
